services:
  # Database Services
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Storage Services
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Tools
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USER: postgres
    depends_on:
      postgres:
        condition: service_healthy

  # Application Services
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      JWT_SECRET: your_jwt_secret_here
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_here
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  plugins:
    build:
      context: .
      dockerfile: apps/plugins/Dockerfile
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:example@mongo:27017/plugins?authSource=admin
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      JWT_SECRET: your_jwt_secret_here
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:4000
      VITE_PLUGINS_API_URL: http://localhost:5000
    depends_on:
      - api
      - plugins
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  minio_data:
