/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./app/__root";
import { Route as RegisterIndexRouteImport } from "./app/register/index";
import { Route as OnboardingIndexRouteImport } from "./app/onboarding/index";
import { Route as LoginIndexRouteImport } from "./app/login/index";
import { Route as AdminIndexRouteImport } from "./app/admin/index";
import { Route as AdminLayoutRouteImport } from "./app/admin/layout";
import { Route as AdminUsersIndexRouteImport } from "./app/admin/users/index";
import { Route as AdminSettingsIndexRouteImport } from "./app/admin/settings/index";
import { Route as AdminEventsIndexRouteImport } from "./app/admin/events/index";
import { Route as AdminDepartmentsIndexRouteImport } from "./app/admin/departments/index";
import { Route as AdminCreateEventIndexRouteImport } from "./app/admin/create-event/index";
import { Route as AdminAuthDiagnosticsIndexRouteImport } from "./app/admin/auth-diagnostics/index";
import { Route as AdminActivityIndexRouteImport } from "./app/admin/activity/index";
import { Route as AdminUsersChar91idChar93IndexRouteImport } from "./app/admin/users/[id]/index";
import { Route as AdminSettingsPluginsIndexRouteImport } from "./app/admin/settings/plugins/index";
import { Route as AdminEventsNewIndexRouteImport } from "./app/admin/events/new/index";
import { Route as AdminEventsChar91idChar93IndexRouteImport } from "./app/admin/events/[id]/index";
import { Route as AdminDepartmentsNewIndexRouteImport } from "./app/admin/departments/new/index";
import { Route as AdminDepartmentsChar91idChar93IndexRouteImport } from "./app/admin/departments/[id]/index";
import { Route as AdminSettingsPluginsSubmitIndexRouteImport } from "./app/admin/settings/plugins/submit/index";
import { Route as AdminSettingsPluginsChar91idChar93IndexRouteImport } from "./app/admin/settings/plugins/[id]/index";
import { Route as AdminEventsChar91idChar93EditIndexRouteImport } from "./app/admin/events/[id]/edit/index";

// Create/Update Routes

const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: "/register/",
  path: "/register/",
  getParentRoute: () => rootRoute,
} as any);

const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/onboarding/",
  path: "/onboarding/",
  getParentRoute: () => rootRoute,
} as any);

const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRoute,
} as any);

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRoute,
} as any);

const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: "/admin/layout",
  path: "/admin/layout",
  getParentRoute: () => rootRoute,
} as any);

const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: "/admin/users/",
  path: "/admin/users/",
  getParentRoute: () => rootRoute,
} as any);

const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: "/admin/settings/",
  path: "/admin/settings/",
  getParentRoute: () => rootRoute,
} as any);

const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: "/admin/events/",
  path: "/admin/events/",
  getParentRoute: () => rootRoute,
} as any);

const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: "/admin/departments/",
  path: "/admin/departments/",
  getParentRoute: () => rootRoute,
} as any);

const AdminCreateEventIndexRoute = AdminCreateEventIndexRouteImport.update({
  id: "/admin/create-event/",
  path: "/admin/create-event/",
  getParentRoute: () => rootRoute,
} as any);

const AdminAuthDiagnosticsIndexRoute =
  AdminAuthDiagnosticsIndexRouteImport.update({
    id: "/admin/auth-diagnostics/",
    path: "/admin/auth-diagnostics/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: "/admin/activity/",
  path: "/admin/activity/",
  getParentRoute: () => rootRoute,
} as any);

const AdminUsersChar91idChar93IndexRoute =
  AdminUsersChar91idChar93IndexRouteImport.update({
    id: "/admin/users/[id]/",
    path: "/admin/users/[id]/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminSettingsPluginsIndexRoute =
  AdminSettingsPluginsIndexRouteImport.update({
    id: "/admin/settings/plugins/",
    path: "/admin/settings/plugins/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminEventsNewIndexRoute = AdminEventsNewIndexRouteImport.update({
  id: "/admin/events/new/",
  path: "/admin/events/new/",
  getParentRoute: () => rootRoute,
} as any);

const AdminEventsChar91idChar93IndexRoute =
  AdminEventsChar91idChar93IndexRouteImport.update({
    id: "/admin/events/[id]/",
    path: "/admin/events/[id]/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminDepartmentsNewIndexRoute =
  AdminDepartmentsNewIndexRouteImport.update({
    id: "/admin/departments/new/",
    path: "/admin/departments/new/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminDepartmentsChar91idChar93IndexRoute =
  AdminDepartmentsChar91idChar93IndexRouteImport.update({
    id: "/admin/departments/[id]/",
    path: "/admin/departments/[id]/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminSettingsPluginsSubmitIndexRoute =
  AdminSettingsPluginsSubmitIndexRouteImport.update({
    id: "/admin/settings/plugins/submit/",
    path: "/admin/settings/plugins/submit/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminSettingsPluginsChar91idChar93IndexRoute =
  AdminSettingsPluginsChar91idChar93IndexRouteImport.update({
    id: "/admin/settings/plugins/[id]/",
    path: "/admin/settings/plugins/[id]/",
    getParentRoute: () => rootRoute,
  } as any);

const AdminEventsChar91idChar93EditIndexRoute =
  AdminEventsChar91idChar93EditIndexRouteImport.update({
    id: "/admin/events/[id]/edit/",
    path: "/admin/events/[id]/edit/",
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/admin/layout": {
      id: "/admin/layout";
      path: "/admin/layout";
      fullPath: "/admin/layout";
      preLoaderRoute: typeof AdminLayoutRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/onboarding/": {
      id: "/onboarding/";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/register/": {
      id: "/register/";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/activity/": {
      id: "/admin/activity/";
      path: "/admin/activity";
      fullPath: "/admin/activity";
      preLoaderRoute: typeof AdminActivityIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/auth-diagnostics/": {
      id: "/admin/auth-diagnostics/";
      path: "/admin/auth-diagnostics";
      fullPath: "/admin/auth-diagnostics";
      preLoaderRoute: typeof AdminAuthDiagnosticsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/create-event/": {
      id: "/admin/create-event/";
      path: "/admin/create-event";
      fullPath: "/admin/create-event";
      preLoaderRoute: typeof AdminCreateEventIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/departments/": {
      id: "/admin/departments/";
      path: "/admin/departments";
      fullPath: "/admin/departments";
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/events/": {
      id: "/admin/events/";
      path: "/admin/events";
      fullPath: "/admin/events";
      preLoaderRoute: typeof AdminEventsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/settings/": {
      id: "/admin/settings/";
      path: "/admin/settings";
      fullPath: "/admin/settings";
      preLoaderRoute: typeof AdminSettingsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/users/": {
      id: "/admin/users/";
      path: "/admin/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/departments/[id]/": {
      id: "/admin/departments/[id]/";
      path: "/admin/departments/[id]";
      fullPath: "/admin/departments/[id]";
      preLoaderRoute: typeof AdminDepartmentsChar91idChar93IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/departments/new/": {
      id: "/admin/departments/new/";
      path: "/admin/departments/new";
      fullPath: "/admin/departments/new";
      preLoaderRoute: typeof AdminDepartmentsNewIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/events/[id]/": {
      id: "/admin/events/[id]/";
      path: "/admin/events/[id]";
      fullPath: "/admin/events/[id]";
      preLoaderRoute: typeof AdminEventsChar91idChar93IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/events/new/": {
      id: "/admin/events/new/";
      path: "/admin/events/new";
      fullPath: "/admin/events/new";
      preLoaderRoute: typeof AdminEventsNewIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/settings/plugins/": {
      id: "/admin/settings/plugins/";
      path: "/admin/settings/plugins";
      fullPath: "/admin/settings/plugins";
      preLoaderRoute: typeof AdminSettingsPluginsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/users/[id]/": {
      id: "/admin/users/[id]/";
      path: "/admin/users/[id]";
      fullPath: "/admin/users/[id]";
      preLoaderRoute: typeof AdminUsersChar91idChar93IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/events/[id]/edit/": {
      id: "/admin/events/[id]/edit/";
      path: "/admin/events/[id]/edit";
      fullPath: "/admin/events/[id]/edit";
      preLoaderRoute: typeof AdminEventsChar91idChar93EditIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/settings/plugins/[id]/": {
      id: "/admin/settings/plugins/[id]/";
      path: "/admin/settings/plugins/[id]";
      fullPath: "/admin/settings/plugins/[id]";
      preLoaderRoute: typeof AdminSettingsPluginsChar91idChar93IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/settings/plugins/submit/": {
      id: "/admin/settings/plugins/submit/";
      path: "/admin/settings/plugins/submit";
      fullPath: "/admin/settings/plugins/submit";
      preLoaderRoute: typeof AdminSettingsPluginsSubmitIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module "./app/admin/layout" {
  const createFileRoute: CreateFileRoute<
    "/admin/layout",
    FileRoutesByPath["/admin/layout"]["parentRoute"],
    FileRoutesByPath["/admin/layout"]["id"],
    FileRoutesByPath["/admin/layout"]["path"],
    FileRoutesByPath["/admin/layout"]["fullPath"]
  >;
}
declare module "./app/admin/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/",
    FileRoutesByPath["/admin/"]["parentRoute"],
    FileRoutesByPath["/admin/"]["id"],
    FileRoutesByPath["/admin/"]["path"],
    FileRoutesByPath["/admin/"]["fullPath"]
  >;
}
declare module "./app/login/index" {
  const createFileRoute: CreateFileRoute<
    "/login/",
    FileRoutesByPath["/login/"]["parentRoute"],
    FileRoutesByPath["/login/"]["id"],
    FileRoutesByPath["/login/"]["path"],
    FileRoutesByPath["/login/"]["fullPath"]
  >;
}
declare module "./app/onboarding/index" {
  const createFileRoute: CreateFileRoute<
    "/onboarding/",
    FileRoutesByPath["/onboarding/"]["parentRoute"],
    FileRoutesByPath["/onboarding/"]["id"],
    FileRoutesByPath["/onboarding/"]["path"],
    FileRoutesByPath["/onboarding/"]["fullPath"]
  >;
}
declare module "./app/register/index" {
  const createFileRoute: CreateFileRoute<
    "/register/",
    FileRoutesByPath["/register/"]["parentRoute"],
    FileRoutesByPath["/register/"]["id"],
    FileRoutesByPath["/register/"]["path"],
    FileRoutesByPath["/register/"]["fullPath"]
  >;
}
declare module "./app/admin/activity/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/activity/",
    FileRoutesByPath["/admin/activity/"]["parentRoute"],
    FileRoutesByPath["/admin/activity/"]["id"],
    FileRoutesByPath["/admin/activity/"]["path"],
    FileRoutesByPath["/admin/activity/"]["fullPath"]
  >;
}
declare module "./app/admin/auth-diagnostics/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/auth-diagnostics/",
    FileRoutesByPath["/admin/auth-diagnostics/"]["parentRoute"],
    FileRoutesByPath["/admin/auth-diagnostics/"]["id"],
    FileRoutesByPath["/admin/auth-diagnostics/"]["path"],
    FileRoutesByPath["/admin/auth-diagnostics/"]["fullPath"]
  >;
}
declare module "./app/admin/create-event/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/create-event/",
    FileRoutesByPath["/admin/create-event/"]["parentRoute"],
    FileRoutesByPath["/admin/create-event/"]["id"],
    FileRoutesByPath["/admin/create-event/"]["path"],
    FileRoutesByPath["/admin/create-event/"]["fullPath"]
  >;
}
declare module "./app/admin/departments/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/departments/",
    FileRoutesByPath["/admin/departments/"]["parentRoute"],
    FileRoutesByPath["/admin/departments/"]["id"],
    FileRoutesByPath["/admin/departments/"]["path"],
    FileRoutesByPath["/admin/departments/"]["fullPath"]
  >;
}
declare module "./app/admin/events/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/events/",
    FileRoutesByPath["/admin/events/"]["parentRoute"],
    FileRoutesByPath["/admin/events/"]["id"],
    FileRoutesByPath["/admin/events/"]["path"],
    FileRoutesByPath["/admin/events/"]["fullPath"]
  >;
}
declare module "./app/admin/settings/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/settings/",
    FileRoutesByPath["/admin/settings/"]["parentRoute"],
    FileRoutesByPath["/admin/settings/"]["id"],
    FileRoutesByPath["/admin/settings/"]["path"],
    FileRoutesByPath["/admin/settings/"]["fullPath"]
  >;
}
declare module "./app/admin/users/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/users/",
    FileRoutesByPath["/admin/users/"]["parentRoute"],
    FileRoutesByPath["/admin/users/"]["id"],
    FileRoutesByPath["/admin/users/"]["path"],
    FileRoutesByPath["/admin/users/"]["fullPath"]
  >;
}
declare module "./app/admin/departments/[id]/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/departments/[id]/",
    FileRoutesByPath["/admin/departments/[id]/"]["parentRoute"],
    FileRoutesByPath["/admin/departments/[id]/"]["id"],
    FileRoutesByPath["/admin/departments/[id]/"]["path"],
    FileRoutesByPath["/admin/departments/[id]/"]["fullPath"]
  >;
}
declare module "./app/admin/departments/new/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/departments/new/",
    FileRoutesByPath["/admin/departments/new/"]["parentRoute"],
    FileRoutesByPath["/admin/departments/new/"]["id"],
    FileRoutesByPath["/admin/departments/new/"]["path"],
    FileRoutesByPath["/admin/departments/new/"]["fullPath"]
  >;
}
declare module "./app/admin/events/[id]/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/events/[id]/",
    FileRoutesByPath["/admin/events/[id]/"]["parentRoute"],
    FileRoutesByPath["/admin/events/[id]/"]["id"],
    FileRoutesByPath["/admin/events/[id]/"]["path"],
    FileRoutesByPath["/admin/events/[id]/"]["fullPath"]
  >;
}
declare module "./app/admin/events/new/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/events/new/",
    FileRoutesByPath["/admin/events/new/"]["parentRoute"],
    FileRoutesByPath["/admin/events/new/"]["id"],
    FileRoutesByPath["/admin/events/new/"]["path"],
    FileRoutesByPath["/admin/events/new/"]["fullPath"]
  >;
}
declare module "./app/admin/settings/plugins/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/settings/plugins/",
    FileRoutesByPath["/admin/settings/plugins/"]["parentRoute"],
    FileRoutesByPath["/admin/settings/plugins/"]["id"],
    FileRoutesByPath["/admin/settings/plugins/"]["path"],
    FileRoutesByPath["/admin/settings/plugins/"]["fullPath"]
  >;
}
declare module "./app/admin/users/[id]/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/users/[id]/",
    FileRoutesByPath["/admin/users/[id]/"]["parentRoute"],
    FileRoutesByPath["/admin/users/[id]/"]["id"],
    FileRoutesByPath["/admin/users/[id]/"]["path"],
    FileRoutesByPath["/admin/users/[id]/"]["fullPath"]
  >;
}
declare module "./app/admin/events/[id]/edit/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/events/[id]/edit/",
    FileRoutesByPath["/admin/events/[id]/edit/"]["parentRoute"],
    FileRoutesByPath["/admin/events/[id]/edit/"]["id"],
    FileRoutesByPath["/admin/events/[id]/edit/"]["path"],
    FileRoutesByPath["/admin/events/[id]/edit/"]["fullPath"]
  >;
}
declare module "./app/admin/settings/plugins/[id]/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/settings/plugins/[id]/",
    FileRoutesByPath["/admin/settings/plugins/[id]/"]["parentRoute"],
    FileRoutesByPath["/admin/settings/plugins/[id]/"]["id"],
    FileRoutesByPath["/admin/settings/plugins/[id]/"]["path"],
    FileRoutesByPath["/admin/settings/plugins/[id]/"]["fullPath"]
  >;
}
declare module "./app/admin/settings/plugins/submit/index" {
  const createFileRoute: CreateFileRoute<
    "/admin/settings/plugins/submit/",
    FileRoutesByPath["/admin/settings/plugins/submit/"]["parentRoute"],
    FileRoutesByPath["/admin/settings/plugins/submit/"]["id"],
    FileRoutesByPath["/admin/settings/plugins/submit/"]["path"],
    FileRoutesByPath["/admin/settings/plugins/submit/"]["fullPath"]
  >;
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/admin/layout": typeof AdminLayoutRoute;
  "/admin": typeof AdminIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/onboarding": typeof OnboardingIndexRoute;
  "/register": typeof RegisterIndexRoute;
  "/admin/activity": typeof AdminActivityIndexRoute;
  "/admin/auth-diagnostics": typeof AdminAuthDiagnosticsIndexRoute;
  "/admin/create-event": typeof AdminCreateEventIndexRoute;
  "/admin/departments": typeof AdminDepartmentsIndexRoute;
  "/admin/events": typeof AdminEventsIndexRoute;
  "/admin/settings": typeof AdminSettingsIndexRoute;
  "/admin/users": typeof AdminUsersIndexRoute;
  "/admin/departments/[id]": typeof AdminDepartmentsChar91idChar93IndexRoute;
  "/admin/departments/new": typeof AdminDepartmentsNewIndexRoute;
  "/admin/events/[id]": typeof AdminEventsChar91idChar93IndexRoute;
  "/admin/events/new": typeof AdminEventsNewIndexRoute;
  "/admin/settings/plugins": typeof AdminSettingsPluginsIndexRoute;
  "/admin/users/[id]": typeof AdminUsersChar91idChar93IndexRoute;
  "/admin/events/[id]/edit": typeof AdminEventsChar91idChar93EditIndexRoute;
  "/admin/settings/plugins/[id]": typeof AdminSettingsPluginsChar91idChar93IndexRoute;
  "/admin/settings/plugins/submit": typeof AdminSettingsPluginsSubmitIndexRoute;
}

export interface FileRoutesByTo {
  "/admin/layout": typeof AdminLayoutRoute;
  "/admin": typeof AdminIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/onboarding": typeof OnboardingIndexRoute;
  "/register": typeof RegisterIndexRoute;
  "/admin/activity": typeof AdminActivityIndexRoute;
  "/admin/auth-diagnostics": typeof AdminAuthDiagnosticsIndexRoute;
  "/admin/create-event": typeof AdminCreateEventIndexRoute;
  "/admin/departments": typeof AdminDepartmentsIndexRoute;
  "/admin/events": typeof AdminEventsIndexRoute;
  "/admin/settings": typeof AdminSettingsIndexRoute;
  "/admin/users": typeof AdminUsersIndexRoute;
  "/admin/departments/[id]": typeof AdminDepartmentsChar91idChar93IndexRoute;
  "/admin/departments/new": typeof AdminDepartmentsNewIndexRoute;
  "/admin/events/[id]": typeof AdminEventsChar91idChar93IndexRoute;
  "/admin/events/new": typeof AdminEventsNewIndexRoute;
  "/admin/settings/plugins": typeof AdminSettingsPluginsIndexRoute;
  "/admin/users/[id]": typeof AdminUsersChar91idChar93IndexRoute;
  "/admin/events/[id]/edit": typeof AdminEventsChar91idChar93EditIndexRoute;
  "/admin/settings/plugins/[id]": typeof AdminSettingsPluginsChar91idChar93IndexRoute;
  "/admin/settings/plugins/submit": typeof AdminSettingsPluginsSubmitIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/admin/layout": typeof AdminLayoutRoute;
  "/admin/": typeof AdminIndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/register/": typeof RegisterIndexRoute;
  "/admin/activity/": typeof AdminActivityIndexRoute;
  "/admin/auth-diagnostics/": typeof AdminAuthDiagnosticsIndexRoute;
  "/admin/create-event/": typeof AdminCreateEventIndexRoute;
  "/admin/departments/": typeof AdminDepartmentsIndexRoute;
  "/admin/events/": typeof AdminEventsIndexRoute;
  "/admin/settings/": typeof AdminSettingsIndexRoute;
  "/admin/users/": typeof AdminUsersIndexRoute;
  "/admin/departments/[id]/": typeof AdminDepartmentsChar91idChar93IndexRoute;
  "/admin/departments/new/": typeof AdminDepartmentsNewIndexRoute;
  "/admin/events/[id]/": typeof AdminEventsChar91idChar93IndexRoute;
  "/admin/events/new/": typeof AdminEventsNewIndexRoute;
  "/admin/settings/plugins/": typeof AdminSettingsPluginsIndexRoute;
  "/admin/users/[id]/": typeof AdminUsersChar91idChar93IndexRoute;
  "/admin/events/[id]/edit/": typeof AdminEventsChar91idChar93EditIndexRoute;
  "/admin/settings/plugins/[id]/": typeof AdminSettingsPluginsChar91idChar93IndexRoute;
  "/admin/settings/plugins/submit/": typeof AdminSettingsPluginsSubmitIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/admin/layout"
    | "/admin"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/admin/activity"
    | "/admin/auth-diagnostics"
    | "/admin/create-event"
    | "/admin/departments"
    | "/admin/events"
    | "/admin/settings"
    | "/admin/users"
    | "/admin/departments/[id]"
    | "/admin/departments/new"
    | "/admin/events/[id]"
    | "/admin/events/new"
    | "/admin/settings/plugins"
    | "/admin/users/[id]"
    | "/admin/events/[id]/edit"
    | "/admin/settings/plugins/[id]"
    | "/admin/settings/plugins/submit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/admin/layout"
    | "/admin"
    | "/login"
    | "/onboarding"
    | "/register"
    | "/admin/activity"
    | "/admin/auth-diagnostics"
    | "/admin/create-event"
    | "/admin/departments"
    | "/admin/events"
    | "/admin/settings"
    | "/admin/users"
    | "/admin/departments/[id]"
    | "/admin/departments/new"
    | "/admin/events/[id]"
    | "/admin/events/new"
    | "/admin/settings/plugins"
    | "/admin/users/[id]"
    | "/admin/events/[id]/edit"
    | "/admin/settings/plugins/[id]"
    | "/admin/settings/plugins/submit";
  id:
    | "__root__"
    | "/admin/layout"
    | "/admin/"
    | "/login/"
    | "/onboarding/"
    | "/register/"
    | "/admin/activity/"
    | "/admin/auth-diagnostics/"
    | "/admin/create-event/"
    | "/admin/departments/"
    | "/admin/events/"
    | "/admin/settings/"
    | "/admin/users/"
    | "/admin/departments/[id]/"
    | "/admin/departments/new/"
    | "/admin/events/[id]/"
    | "/admin/events/new/"
    | "/admin/settings/plugins/"
    | "/admin/users/[id]/"
    | "/admin/events/[id]/edit/"
    | "/admin/settings/plugins/[id]/"
    | "/admin/settings/plugins/submit/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  LoginIndexRoute: typeof LoginIndexRoute;
  OnboardingIndexRoute: typeof OnboardingIndexRoute;
  RegisterIndexRoute: typeof RegisterIndexRoute;
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute;
  AdminAuthDiagnosticsIndexRoute: typeof AdminAuthDiagnosticsIndexRoute;
  AdminCreateEventIndexRoute: typeof AdminCreateEventIndexRoute;
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute;
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute;
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute;
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute;
  AdminDepartmentsChar91idChar93IndexRoute: typeof AdminDepartmentsChar91idChar93IndexRoute;
  AdminDepartmentsNewIndexRoute: typeof AdminDepartmentsNewIndexRoute;
  AdminEventsChar91idChar93IndexRoute: typeof AdminEventsChar91idChar93IndexRoute;
  AdminEventsNewIndexRoute: typeof AdminEventsNewIndexRoute;
  AdminSettingsPluginsIndexRoute: typeof AdminSettingsPluginsIndexRoute;
  AdminUsersChar91idChar93IndexRoute: typeof AdminUsersChar91idChar93IndexRoute;
  AdminEventsChar91idChar93EditIndexRoute: typeof AdminEventsChar91idChar93EditIndexRoute;
  AdminSettingsPluginsChar91idChar93IndexRoute: typeof AdminSettingsPluginsChar91idChar93IndexRoute;
  AdminSettingsPluginsSubmitIndexRoute: typeof AdminSettingsPluginsSubmitIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
  AdminAuthDiagnosticsIndexRoute: AdminAuthDiagnosticsIndexRoute,
  AdminCreateEventIndexRoute: AdminCreateEventIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminDepartmentsChar91idChar93IndexRoute:
    AdminDepartmentsChar91idChar93IndexRoute,
  AdminDepartmentsNewIndexRoute: AdminDepartmentsNewIndexRoute,
  AdminEventsChar91idChar93IndexRoute: AdminEventsChar91idChar93IndexRoute,
  AdminEventsNewIndexRoute: AdminEventsNewIndexRoute,
  AdminSettingsPluginsIndexRoute: AdminSettingsPluginsIndexRoute,
  AdminUsersChar91idChar93IndexRoute: AdminUsersChar91idChar93IndexRoute,
  AdminEventsChar91idChar93EditIndexRoute:
    AdminEventsChar91idChar93EditIndexRoute,
  AdminSettingsPluginsChar91idChar93IndexRoute:
    AdminSettingsPluginsChar91idChar93IndexRoute,
  AdminSettingsPluginsSubmitIndexRoute: AdminSettingsPluginsSubmitIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin/layout",
        "/admin/",
        "/login/",
        "/onboarding/",
        "/register/",
        "/admin/activity/",
        "/admin/auth-diagnostics/",
        "/admin/create-event/",
        "/admin/departments/",
        "/admin/events/",
        "/admin/settings/",
        "/admin/users/",
        "/admin/departments/[id]/",
        "/admin/departments/new/",
        "/admin/events/[id]/",
        "/admin/events/new/",
        "/admin/settings/plugins/",
        "/admin/users/[id]/",
        "/admin/events/[id]/edit/",
        "/admin/settings/plugins/[id]/",
        "/admin/settings/plugins/submit/"
      ]
    },
    "/admin/layout": {
      "filePath": "admin/layout.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/admin/activity/": {
      "filePath": "admin/activity/index.tsx"
    },
    "/admin/auth-diagnostics/": {
      "filePath": "admin/auth-diagnostics/index.tsx"
    },
    "/admin/create-event/": {
      "filePath": "admin/create-event/index.tsx"
    },
    "/admin/departments/": {
      "filePath": "admin/departments/index.tsx"
    },
    "/admin/events/": {
      "filePath": "admin/events/index.tsx"
    },
    "/admin/settings/": {
      "filePath": "admin/settings/index.tsx"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx"
    },
    "/admin/departments/[id]/": {
      "filePath": "admin/departments/[id]/index.tsx"
    },
    "/admin/departments/new/": {
      "filePath": "admin/departments/new/index.tsx"
    },
    "/admin/events/[id]/": {
      "filePath": "admin/events/[id]/index.tsx"
    },
    "/admin/events/new/": {
      "filePath": "admin/events/new/index.tsx"
    },
    "/admin/settings/plugins/": {
      "filePath": "admin/settings/plugins/index.tsx"
    },
    "/admin/users/[id]/": {
      "filePath": "admin/users/[id]/index.tsx"
    },
    "/admin/events/[id]/edit/": {
      "filePath": "admin/events/[id]/edit/index.tsx"
    },
    "/admin/settings/plugins/[id]/": {
      "filePath": "admin/settings/plugins/[id]/index.tsx"
    },
    "/admin/settings/plugins/submit/": {
      "filePath": "admin/settings/plugins/submit/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
