/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { Activity } from './activity';

export type ActivitiesControllerGetActivities200 = {
  activities?: Activity[];
  /** Total number of activities */
  total?: number;
};
