/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type ActivitiesControllerGetActivitiesSeverity =
  (typeof ActivitiesControllerGetActivitiesSeverity)[keyof typeof ActivitiesControllerGetActivitiesSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivitiesControllerGetActivitiesSeverity = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;
