/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActivitiesControllerGetActivitiesType } from "./activitiesControllerGetActivitiesType";
import type { ActivitiesControllerGetActivitiesSeverity } from "./activitiesControllerGetActivitiesSeverity";

export type ActivitiesControllerGetActivitiesParams = {
  /**
   * Search in description, user name, or email
   */
  search?: string;
  /**
   * Filter by activity type
   */
  type?: ActivitiesControllerGetActivitiesType;
  /**
   * Filter by activity severity
   */
  severity?: ActivitiesControllerGetActivitiesSeverity;
  /**
   * Date range filter (1d, 7d, 30d, 90d)
   */
  dateRange?: string;
  /**
   * Number of activities to return
   */
  limit?: number;
  /**
   * Number of activities to skip
   */
  offset?: number;
};
