/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type ActivitiesControllerGetActivityCounts200 = {
  total?: number;
  financial?: number;
  eventManagement?: number;
  userManagement?: number;
  administrative?: number;
  security?: number;
  marketing?: number;
};
