/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type ActivitiesControllerGetActivityCountsParams = {
/**
 * Date range filter (1d, 7d, 30d, 90d)
 */
dateRange?: string;
};
