/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { AddCartItemDtoType } from './addCartItemDtoType';
import type { AddCartItemDtoMetadata } from './addCartItemDtoMetadata';

export interface AddCartItemDto {
  /** Ticket type ID (for ticket items) */
  ticketTypeId?: string;
  /** Item name */
  name: string;
  /** Quantity */
  quantity: number;
  /** Unit price */
  unitPrice: number;
  /** Item type */
  type: AddCartItemDtoType;
  /** Additional metadata (JSON) */
  metadata?: AddCartItemDtoMetadata;
}
