/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Item type
 */
export type AddCartItemDtoType = typeof AddCartItemDtoType[keyof typeof AddCartItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddCartItemDtoType = {
  ticket: 'ticket',
  merchandise: 'merchandise',
  fee: 'fee',
} as const;
