/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type AnalyticsControllerGetRevenueChartDataGranularity = typeof AnalyticsControllerGetRevenueChartDataGranularity[keyof typeof AnalyticsControllerGetRevenueChartDataGranularity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsControllerGetRevenueChartDataGranularity = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
