/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { AnalyticsControllerGetRevenueChartDataGranularity } from './analyticsControllerGetRevenueChartDataGranularity';

export type AnalyticsControllerGetRevenueChartDataParams = {
/**
 * Start date (ISO string)
 */
start: string;
/**
 * End date (ISO string)
 */
end: string;
/**
 * Data granularity
 */
granularity?: AnalyticsControllerGetRevenueChartDataGranularity;
};
