/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { AudienceAnalyticsDtoAgeDistribution } from "./audienceAnalyticsDtoAgeDistribution";
import type { AudienceAnalyticsDtoGenderDistribution } from "./audienceAnalyticsDtoGenderDistribution";
import type { AudienceAnalyticsDtoGeographicDistribution } from "./audienceAnalyticsDtoGeographicDistribution";
import type { AudienceAnalyticsDtoDeviceDistribution } from "./audienceAnalyticsDtoDeviceDistribution";
import type { AudienceAnalyticsDtoEngagement } from "./audienceAnalyticsDtoEngagement";

export interface AudienceAnalyticsDto {
  /** Total number of unique visitors */
  totalVisitors: number;
  /** Age distribution of visitors */
  ageDistribution: AudienceAnalyticsDtoAgeDistribution;
  /** Gender distribution of visitors */
  genderDistribution: AudienceAnalyticsDtoGenderDistribution;
  /** Geographic distribution of visitors */
  geographicDistribution: AudienceAnalyticsDtoGeographicDistribution;
  /** Device types used by visitors */
  deviceDistribution: AudienceAnalyticsDtoDeviceDistribution;
  /** Visitor engagement metrics */
  engagement: AudienceAnalyticsDtoEngagement;
}
