/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { CartItem } from './cartItem';
import type { CartCustomer } from './cartCustomer';
import type { CartStatus } from './cartStatus';

export interface Cart {
  /** Unique identifier */
  id: string;
  /** Organization ID */
  organizationId: string;
  /** Event ID */
  eventId: string;
  /** User ID (optional for guest checkout) */
  userId?: string;
  /** Session ID for tracking anonymous carts */
  sessionId: string;
  /** Cart items */
  items: CartItem[];
  /** Customer information (JSON) */
  customer?: CartCustomer;
  /** Subtotal amount */
  subtotal: number;
  /** Service fees amount */
  fees: number;
  /** Tax amount */
  taxes: number;
  /** Total amount */
  total: number;
  /** Currency */
  currency: string;
  /** Discount code (if applied) */
  discountCode?: string;
  /** Discount amount */
  discountAmount?: number;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Expiration timestamp */
  expiresAt: string;
  /** Cart status */
  status: CartStatus;
}
