/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { CartItemType } from './cartItemType';
import type { CartItemMetadata } from './cartItemMetadata';

export interface CartItem {
  /** Unique identifier */
  id: string;
  /** Cart ID */
  cartId: string;
  /** Ticket type ID */
  ticketTypeId?: string;
  /** Item name */
  name: string;
  /** Quantity */
  quantity: number;
  /** Unit price */
  unitPrice: number;
  /** Subtotal */
  subtotal: number;
  /** Item type */
  type: CartItemType;
  /** Additional metadata (JSON) */
  metadata?: CartItemMetadata;
}
