/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Cart status
 */
export type CartStatus = typeof CartStatus[keyof typeof CartStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartStatus = {
  active: 'active',
  abandoned: 'abandoned',
  converted: 'converted',
  expired: 'expired',
} as const;
