/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreatePluginDtoCategory } from "./createPluginDtoCategory";
import type { CreatePluginDtoAdminComponents } from "./createPluginDtoAdminComponents";
import type { CreatePluginDtoStorefrontComponents } from "./createPluginDtoStorefrontComponents";
import type { CreatePluginDtoMetadata } from "./createPluginDtoMetadata";

export interface CreatePluginDto {
  /** Plugin name */
  name: string;
  /** Plugin version */
  version: string;
  /** Plugin description */
  description: string;
  /** Plugin category */
  category: CreatePluginDtoCategory;
  /** URL to the plugin bundle */
  bundleUrl: string;
  /** List of extension points this plugin implements */
  extensionPoints: string[];
  /** Admin components provided by the plugin */
  adminComponents: CreatePluginDtoAdminComponents;
  /** Storefront components provided by the plugin */
  storefrontComponents: CreatePluginDtoStorefrontComponents;
  /** Metadata about the plugin */
  metadata: CreatePluginDtoMetadata;
  /** Required permissions for this plugin */
  requiredPermissions?: string[];
}
