/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateCartDto {
  /** Organization ID */
  organizationId: string;
  /** Event ID */
  eventId: string;
  /** User ID (optional for guest checkout) */
  userId?: string;
  /** Session ID for tracking anonymous carts */
  sessionId?: string;
}
