/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentIntentDtoMetadata } from "./createPaymentIntentDtoMetadata";

export interface CreatePaymentIntentDto {
  /** Organization ID */
  organizationId: string;
  /** Amount to charge */
  amount: number;
  /** Currency code */
  currency: string;
  /** Additional metadata for the payment intent */
  metadata?: CreatePaymentIntentDtoMetadata;
}
