/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Date range type
 */
export type DateRangeType = (typeof DateRangeType)[keyof typeof DateRangeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DateRangeType = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
} as const;
