/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { DepartmentSettings } from "./departmentSettings";

export interface Department {
  /** Unique identifier for the department */
  id: string;
  /** Department name */
  name: string;
  /** Department description */
  description?: string;
  /** URL-friendly identifier */
  slug: string;
  /** ID of the organization the department belongs to */
  organizationId: string;
  /** Department head user ID */
  headId?: string;
  /** Parent department ID */
  parentDepartmentId?: string;
  /** Department code or identifier */
  code?: string;
  /** When the department was created */
  createdAt: string;
  /** When the department was last updated */
  updatedAt: string;
  /** Department settings and metadata */
  settings: DepartmentSettings;
  /** Whether the department is active */
  isActive: boolean;
}
