/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { DepartmentCustomFieldDtoType } from "./departmentCustomFieldDtoType";

export interface DepartmentCustomFieldDto {
  /** Field key */
  key: string;
  /** Field label */
  label: string;
  /** Field type */
  type: DepartmentCustomFieldDtoType;
  /** Field options for select type */
  options?: string[];
  /** Whether the field is required */
  required?: boolean;
}
