/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { DepartmentNotificationPreferencesDto } from "./departmentNotificationPreferencesDto";
import type { DepartmentCustomFieldDto } from "./departmentCustomFieldDto";

export interface DepartmentSettingsDto {
  /** Department color */
  color?: string;
  /** Department icon */
  icon?: string;
  /** Contact email */
  contactEmail?: string;
  /** Contact phone */
  contactPhone?: string;
  /** Department location */
  location?: string;
  /** Default ticket assignee ID */
  defaultTicketAssignee?: string;
  /** Auto-assign tickets */
  autoAssignTickets?: boolean;
  /** Notification preferences */
  notificationPreferences?: DepartmentNotificationPreferencesDto;
  /** Custom fields */
  customFields?: DepartmentCustomFieldDto[];
}
