/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Field type
 */
export type DepartmentCustomFieldDtoType = typeof DepartmentCustomFieldDtoType[keyof typeof DepartmentCustomFieldDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DepartmentCustomFieldDtoType = {
  text: 'text',
  number: 'number',
  date: 'date',
  boolean: 'boolean',
  select: 'select',
} as const;
