/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { EventAnalyticsTicketTypeBreakdown } from './eventAnalyticsTicketTypeBreakdown';
import type { EventAnalyticsReferrers } from './eventAnalyticsReferrers';

export interface EventAnalytics {
  /** Unique identifier */
  id: string;
  /** Event ID */
  eventId: string;
  /** Organization ID */
  organizationId: string;
  /** Date of analytics data */
  date: string;
  /** Total page views */
  totalViews: number;
  /** Unique page views */
  uniqueViews: number;
  /** Total sales count */
  totalSales: number;
  /** Number of tickets sold */
  ticketsSold: number;
  /** Conversion rate (percentage) */
  conversionRate: number;
  /** Total revenue */
  revenue: number;
  /** Breakdown of ticket types sold */
  ticketTypeBreakdown: EventAnalyticsTicketTypeBreakdown;
  /** Number of refunds */
  refunds: number;
  /** Traffic referrers */
  referrers: EventAnalyticsReferrers;
  /** Creation/Update timestamp */
  createdAt: string;
}
