/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the event
 */
export type EventResponseDtoStatus =
  (typeof EventResponseDtoStatus)[keyof typeof EventResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventResponseDtoStatus = {
  draft: "draft",
  published: "published",
  cancelled: "cancelled",
  completed: "completed",
} as const;
