/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Visibility setting of the event
 */
export type EventResponseDtoVisibility = typeof EventResponseDtoVisibility[keyof typeof EventResponseDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventResponseDtoVisibility = {
  public: 'public',
  private: 'private',
  unlisted: 'unlisted',
} as const;
