/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type EventsControllerFindAllStatus =
  (typeof EventsControllerFindAllStatus)[keyof typeof EventsControllerFindAllStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventsControllerFindAllStatus = {
  draft: "draft",
  published: "published",
  cancelled: "cancelled",
  completed: "completed",
} as const;
