/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Type of event location
 */
export type EventResponseDtoLocationType =
  (typeof EventResponseDtoLocationType)[keyof typeof EventResponseDtoLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventResponseDtoLocationType = {
  physical: "physical",
  virtual: "virtual",
  hybrid: "hybrid",
} as const;
