/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { InstalledPluginDtoCategory } from './installedPluginDtoCategory';
import type { InstalledPluginDtoStatus } from './installedPluginDtoStatus';
import type { InstalledPluginDtoConfiguration } from './installedPluginDtoConfiguration';
import type { InstalledPluginDtoMetadata } from './installedPluginDtoMetadata';

export interface InstalledPluginDto {
  /** Unique identifier for the installed plugin */
  id: string;
  /** Plugin ID reference */
  pluginId: string;
  /** Organization ID that installed the plugin */
  organizationId: string;
  /** Plugin name */
  name: string;
  /** Plugin version */
  version: string;
  /** Plugin description */
  description: string;
  /** Plugin category */
  category: InstalledPluginDtoCategory;
  /** Plugin status */
  status: InstalledPluginDtoStatus;
  /** Whether the plugin is enabled */
  enabled: boolean;
  /** Plugin configuration */
  configuration: InstalledPluginDtoConfiguration;
  /** Installation date */
  installedAt: string;
  /** Last update date */
  updatedAt: string;
  /** Plugin metadata */
  metadata: InstalledPluginDtoMetadata;
}
