/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Plugin category
 */
export type InstalledPluginDtoCategory = typeof InstalledPluginDtoCategory[keyof typeof InstalledPluginDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InstalledPluginDtoCategory = {
  payment: 'payment',
  notification: 'notification',
  analytics: 'analytics',
  integration: 'integration',
  ui: 'ui',
  workflow: 'workflow',
} as const;
