/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Organization plan type
 */
export type OrganizationPlan = typeof OrganizationPlan[keyof typeof OrganizationPlan];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationPlan = {
  free: 'free',
  basic: 'basic',
  pro: 'pro',
  enterprise: 'enterprise',
} as const;
