/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationAddress } from "./organizationAddress";
import type { OrganizationPlan } from "./organizationPlan";
import type { OrganizationSettings } from "./organizationSettings";

export interface Organization {
  /** Unique identifier for the organization */
  id: string;
  /** Organization name */
  name: string;
  /** URL-friendly identifier */
  slug: string;
  /** Organization email */
  email: string;
  /** Organization phone */
  phone?: string;
  /** Organization website */
  website?: string;
  /** Organization address */
  address?: OrganizationAddress;
  /** Organization logo URL */
  logo?: string;
  /** Organization favicon URL */
  favicon?: string;
  /** When the organization was created */
  createdAt: string;
  /** When the organization was last updated */
  updatedAt: string;
  /** Organization plan type */
  plan: OrganizationPlan;
  /** Organization settings */
  settings: OrganizationSettings;
  /** Subscription ID */
  subscriptionId?: string;
  /** Custom domain */
  customDomain?: string;
  /** Domain verification status */
  domainVerified?: boolean;
  /** Domain verification token */
  domainVerificationToken?: string;
  /** Default checkout message */
  checkoutMessage?: string;
  /** Default confirmation email template */
  emailTemplate?: string;
}
