/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type PaymentsControllerGetTransactionsByOrganizationParams = {
fromDate?: string;
toDate?: string;
};
