/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { PaymentConfirmationResponseDtoStatus } from "./paymentConfirmationResponseDtoStatus";
import type { PaymentConfirmationResponseDtoPaymentData } from "./paymentConfirmationResponseDtoPaymentData";

export interface PaymentConfirmationResponseDto {
  /** Status of the payment */
  status: PaymentConfirmationResponseDtoStatus;
  /** Additional payment data from the provider */
  paymentData: PaymentConfirmationResponseDtoPaymentData;
}
