/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the payment
 */
export type PaymentConfirmationResponseDtoStatus =
  (typeof PaymentConfirmationResponseDtoStatus)[keyof typeof PaymentConfirmationResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentConfirmationResponseDtoStatus = {
  succeeded: "succeeded",
  processing: "processing",
  requires_payment_method: "requires_payment_method",
  requires_confirmation: "requires_confirmation",
  canceled: "canceled",
} as const;
