/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export interface PaymentIntentResponseDto {
  /** Client secret for the payment intent */
  clientSecret: string;
  /** ID of the payment intent */
  paymentIntentId: string;
  /** Name of the payment provider */
  providerName: string;
}
