/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Plugin status
 */
export type PluginStatus = typeof PluginStatus[keyof typeof PluginStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PluginStatus = {
  active: 'active',
  inactive: 'inactive',
  deprecated: 'deprecated',
  removed: 'removed',
} as const;
