/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { PluginCategory } from './pluginCategory';
import type { PluginStatus } from './pluginStatus';
import type { PluginResponseDtoMetadata } from './pluginResponseDtoMetadata';

export interface PluginResponseDto {
  /** Unique identifier */
  id: string;
  /** Plugin name */
  name: string;
  /** Plugin version */
  version: string;
  /** Plugin description */
  description: string;
  /** Plugin category */
  category: PluginCategory;
  /** Plugin status */
  status: PluginStatus;
  /** URL to the plugin bundle */
  bundleUrl?: string;
  /** List of extension points this plugin implements */
  extensionPoints: string[];
  /** Required permissions for this plugin */
  requiredPermissions: string[];
  /** Metadata about the plugin */
  metadata?: PluginResponseDtoMetadata;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
