/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type PluginsControllerFindAllStatus =
  (typeof PluginsControllerFindAllStatus)[keyof typeof PluginsControllerFindAllStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PluginsControllerFindAllStatus = {
  active: "active",
  inactive: "inactive",
  deprecated: "deprecated",
  removed: "removed",
} as const;
