/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type PluginsControllerUploadStorage201 = {
  /** URL to the stored bundle */
  bundleUrl?: string;
  /** Plugin ID used for storage */
  pluginId?: string;
  /** Version used for storage */
  version?: string;
};
