/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { PluginProxyResponseDtoData } from './pluginProxyResponseDtoData';
import type { PluginProxyResponseDtoHeaders } from './pluginProxyResponseDtoHeaders';

export interface PluginProxyResponseDto {
  /** HTTP status code of the proxied response */
  status: number;
  /** Response data from the plugin */
  data: PluginProxyResponseDtoData;
  /** Response headers from the plugin */
  headers: PluginProxyResponseDtoHeaders;
}
