/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type PluginsControllerUploadStorageBody = {
  /** Plugin bundle file (JavaScript) */
  file?: Blob;
  /** Plugin ID for storage path */
  pluginId?: string;
  /** Plugin version for storage path */
  version?: string;
};
