/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export type PluginsControllerCreateMetadataBody = {
  /** Plugin ID */
  id: string;
  /** Plugin name */
  name: string;
  /** Plugin version */
  version: string;
  /** Plugin description */
  description: string;
  /** Plugin category */
  category: string;
  /** Plugin source code */
  sourceCode: string;
  /** URL to the plugin bundle */
  bundleUrl: string;
  /** Required permissions */
  requiredPermissions?: string[];
};
