/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export interface RefreshTokenDto {
  /** Refresh token received from login or registration */
  refreshToken: string;
}
