/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Plugin category
 */
export type RegisterPaymentPluginDtoCategory = typeof RegisterPaymentPluginDtoCategory[keyof typeof RegisterPaymentPluginDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterPaymentPluginDtoCategory = {
  payment: 'payment',
  marketing: 'marketing',
  analytics: 'analytics',
  social: 'social',
  ticketing: 'ticketing',
  layout: 'layout',
  seating: 'seating',
} as const;
