/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { RegisterPaymentPluginDtoCategory } from "./registerPaymentPluginDtoCategory";
import type { RegisterPaymentPluginDtoAdminComponents } from "./registerPaymentPluginDtoAdminComponents";
import type { RegisterPaymentPluginDtoStorefrontComponents } from "./registerPaymentPluginDtoStorefrontComponents";
import type { RegisterPaymentPluginDtoMetadata } from "./registerPaymentPluginDtoMetadata";
import type { RegisterPaymentPluginDtoProvider } from "./registerPaymentPluginDtoProvider";
import type { RegisterPaymentPluginDtoConfigurationSchema } from "./registerPaymentPluginDtoConfigurationSchema";
import type { RegisterPaymentPluginDtoDefaultConfiguration } from "./registerPaymentPluginDtoDefaultConfiguration";

export interface RegisterPaymentPluginDto {
  /** Plugin name */
  name: string;
  /** Plugin version */
  version: string;
  /** Plugin description */
  description: string;
  /** Plugin category */
  category: RegisterPaymentPluginDtoCategory;
  /** URL to the plugin bundle */
  bundleUrl: string;
  /** List of extension points this plugin implements */
  extensionPoints: string[];
  /** Admin components provided by the plugin */
  adminComponents: RegisterPaymentPluginDtoAdminComponents;
  /** Storefront components provided by the plugin */
  storefrontComponents: RegisterPaymentPluginDtoStorefrontComponents;
  /** Metadata about the plugin */
  metadata: RegisterPaymentPluginDtoMetadata;
  /** Required permissions for this plugin */
  requiredPermissions?: string[];
  /** Payment provider name */
  provider: RegisterPaymentPluginDtoProvider;
  /** Supported payment methods */
  supportedMethods: string[];
  /** Supported currencies */
  supportedCurrencies: string[];
  /** Gateway-specific configuration schema */
  configurationSchema: RegisterPaymentPluginDtoConfigurationSchema;
  /** Default plugin configuration */
  defaultConfiguration?: RegisterPaymentPluginDtoDefaultConfiguration;
}
