/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Payment provider name
 */
export type RegisterPaymentPluginDtoProvider =
  (typeof RegisterPaymentPluginDtoProvider)[keyof typeof RegisterPaymentPluginDtoProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterPaymentPluginDtoProvider = {
  stripe: "stripe",
  paypal: "paypal",
  authorize_net: "authorize_net",
  square: "square",
  braintree: "braintree",
} as const;
