/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** User full name */
  name: string;
  /** User email address */
  email: string;
  /** User password */
  password: string;
  /** Organization name */
  organizationName: string;
  /** Organization slug (auto-generated if not provided) */
  organizationSlug?: string;
  /** User role within the organization */
  role?: string;
}
