/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { DateRangeType } from "./dateRangeType";
import type { SalesAnalyticsEventBreakdown } from "./salesAnalyticsEventBreakdown";
import type { SalesAnalyticsPaymentMethodBreakdown } from "./salesAnalyticsPaymentMethodBreakdown";

export interface SalesAnalytics {
  /** Unique identifier */
  id: string;
  /** Organization ID */
  organizationId: string;
  /** Date range type */
  dateRange: DateRangeType;
  /** Date of analytics data */
  date: string;
  /** Total sales count */
  totalSales: number;
  /** Total revenue */
  totalRevenue: number;
  /** Total tickets sold */
  ticketsSold: number;
  /** Average order value */
  averageOrderValue: number;
  /** Refund amount */
  refundAmount: number;
  /** Service fees collected */
  feesCollected: number;
  /** Breakdown by event */
  eventBreakdown: SalesAnalyticsEventBreakdown;
  /** Breakdown by payment method */
  paymentMethodBreakdown: SalesAnalyticsPaymentMethodBreakdown;
  /** Creation/Update timestamp */
  createdAt: string;
}
