/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { TransactionType } from "./transactionType";
import type { TransactionStatus } from "./transactionStatus";
import type { TransactionMetadata } from "./transactionMetadata";

export interface Transaction {
  /** Unique identifier */
  id: string;
  /** Organization ID */
  organizationId: string;
  /** Order ID */
  orderId?: string;
  /** User ID (optional for guest checkout) */
  userId?: string;
  /** Transaction type */
  type: TransactionType;
  /** Transaction amount */
  amount: number;
  /** Currency */
  currency: string;
  /** Payment method */
  paymentMethod: string;
  /** Payment method ID from provider */
  paymentMethodId: string;
  /** Payment intent ID from provider */
  paymentIntentId?: string;
  /** Transaction status */
  status: TransactionStatus;
  /** Gateway fee */
  gatewayFee?: number;
  /** Platform fee */
  platformFee?: number;
  /** Additional metadata (JSON) */
  metadata?: TransactionMetadata;
  /** Error message (if transaction failed) */
  errorMessage?: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
