/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateCartItemDtoType } from './updateCartItemDtoType';
import type { UpdateCartItemDtoMetadata } from './updateCartItemDtoMetadata';

export interface UpdateCartItemDto {
  /** Item name */
  name?: string;
  /** Quantity */
  quantity?: number;
  /** Unit price */
  unitPrice?: number;
  /** Item type */
  type?: UpdateCartItemDtoType;
  /** Additional metadata (JSON) */
  metadata?: UpdateCartItemDtoMetadata;
}
