/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { DepartmentSettingsDto } from "./departmentSettingsDto";

export interface UpdateDepartmentDto {
  /** Department name */
  name?: string;
  /** Department description */
  description?: string;
  /** URL-friendly identifier */
  slug?: string;
  /** Organization ID */
  organizationId?: string;
  /** Department head user ID */
  headId?: string;
  /** Parent department ID */
  parentDepartmentId?: string;
  /** Department code or identifier */
  code?: string;
  /** Department settings */
  settings?: DepartmentSettingsDto;
  /** Whether the department is active */
  isActive?: boolean;
}
