/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdatePluginDtoCategory } from "./updatePluginDtoCategory";
import type { UpdatePluginDtoAdminComponents } from "./updatePluginDtoAdminComponents";
import type { UpdatePluginDtoStorefrontComponents } from "./updatePluginDtoStorefrontComponents";
import type { UpdatePluginDtoMetadata } from "./updatePluginDtoMetadata";

export interface UpdatePluginDto {
  /** Plugin name */
  name?: string;
  /** Plugin version */
  version?: string;
  /** Plugin description */
  description?: string;
  /** Plugin category */
  category?: UpdatePluginDtoCategory;
  /** URL to the plugin bundle */
  bundleUrl?: string;
  /** List of extension points this plugin implements */
  extensionPoints?: string[];
  /** Admin components provided by the plugin */
  adminComponents?: UpdatePluginDtoAdminComponents;
  /** Storefront components provided by the plugin */
  storefrontComponents?: UpdatePluginDtoStorefrontComponents;
  /** Metadata about the plugin */
  metadata?: UpdatePluginDtoMetadata;
  /** Required permissions for this plugin */
  requiredPermissions?: string[];
}
