/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * eTickets Platform API
 * The eTickets Platform API documentation
 * OpenAPI spec version: 1.0
 */
import type { UserRole } from './userRole';
import type { UserStatus } from './userStatus';

export interface User {
  /** Unique identifier for the user */
  id: string;
  /** User's full name */
  name: string;
  /** User's email address */
  email: string;
  /** User's hashed password */
  password: string;
  /** User's avatar URL */
  avatar?: string;
  /** User's role in the organization */
  role: UserRole;
  /** User's permissions */
  permissions: string[];
  /** ID of the organization the user belongs to */
  organizationId: string;
  /** ID of the department the user belongs to */
  departmentId?: string;
  /** When the user was created */
  createdAt: string;
  /** When the user was last active */
  lastActive: string;
  /** User's status */
  status: UserStatus;
  /** Whether two-factor authentication is enabled */
  twoFactorEnabled: boolean;
  /** Two-factor authentication secret */
  twoFactorSecret?: string;
}
